using Editor.Model;

namespace Editor
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Application app = new Application();
            app.Run();
        }
    }
}

/* TO DO
 * REFACTOR PREVIEW DRAW (OR ALL OF THE DRAW METHODS)
 * CREATE A CHECK TO SEE IF CHANGED VALUES ARE IN CORRECT FORMAT
 * GET RID OF CONSOLE.CLEAR() AND REPLACE IT WITH A BETTER SOLUTION
 * NICER GRAPHICS EVERYWHERE
 * GET RID OF SEPERATE WINDOW FOR PATH CHANGING, INSTEAD MAKE IT A COMPONENT OF THE EDIT WINDOw
 * IS THERE A WAY TO PUT ALL DIFFERENT DISKS INTO A SINGLE COMBOBOX INSTEAD OF HAVING A SEPERATE COMBOBOX FOR EACH DISK?
 * MOVE BACKUPJOB LIST BACK TO WINDOWLIST AND REWORK EVERYTHING RELATED, BACKUPJOB LIST RELATED METHODS INTO WINDOWLIST AS WELL
 * MANY OTHER THINGS I CAN'T THINK OF RIGHT NOW
 * MOVE BACKUPJOB LIST INTO WINDOWLIST
 * REMOVE RETENTION KNOWING WHO IT BELONGS TO
 */
