using Editor.Model;

namespace Editor
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Application app = new Application();
            app.Run();
        }
    }
}

/* TO DO
 * REFACTOR PREVIEW DRAW (OR ALL OF THE DRAW METHODS)
 * CREATE A CHECK TO SEE IF CHANGED VALUES ARE IN CORRECT FORMAT
 * GET RID OF CONSOLE.CLEAR() AND REPLACE IT WITH A BETTER SOLUTION
 * NICER GRAPHICS EVERYWHERE
 * GET RID OF SEPERATE WINDOW FOR PATH CHANGING, INSTEAD MAKE IT A COMPONENT OF THE EDIT WINDOW
 * MANY DRAW AND HANDLEKEY METHODS ARE VERY SIMILAR, FIND A WAY TO REUSE CODE (ABSTRACT CLASS? INTERFACE? DON'T KNOW YET)
 * MANY OTHER THINGS I CAN'T THINK OF RIGHT NOW
 */
